server:
  port: 8080
spring:
  application:
    name: mypls
  datasource:
    url: jdbc:mysql://localhost:3306/mypls?serverTimezone=PRC&useUnicode=true&characterEncoding=utf8
    name: pls
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
